export const AUTHENTICATE = "AUTHENTICATE";
export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const LOAD_LANGUAGE = "LOAD_LANGUAGE";
export const FETCH_RESERVATIONS = "FETCH_RESERVATIONS";
