export const UPDATE_USER = "UPDATE_USER";
export const CHANGE_LOCALE = "CHANGE_LOCALE";
export const ADD_LOADED_LANGUAGE = "ADD_LOADED_LANGUAGE";
export const UPDATE_LOCATIONS = "UPDATE_LOCATIONS";
export const ABORT_WITH_ERROR = "ABORT_WITH_ERROR";